exporters:
  prometheusremotewrite:
    endpoint: ${LOGZIO_LISTENER}
    headers:
      Authorization: Bearer ${METRICS_TOKEN}
receivers:
  docker_stats:
    api_version: 1.24
    collection_interval: ${COLLECTION_INTERVAL}
    endpoint: ${DOCKER_ENDPOINT}
    excluded_images:
    - pubsub
    - node-dep
    provide_per_core_cpu_metrics: true
    timeout: ${TIMEOUT}
service:
  pipelines:
    metrics:
      exporters:
      - prometheusremotewrite
      receivers:
      - docker_stats
  telemetry:
    logs:
      level: debug
